"""init

Revision ID: 149d8a14e7da
Revises: 0ff859392bd9
Create Date: 2025-03-24 20:25:53.816458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '149d8a14e7da'
down_revision: Union[str, None] = '0ff859392bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_file_id', table_name='media_file')
    op.drop_index('ix_media_file_s3_key', table_name='media_file')
    op.drop_table('media_file')
    op.alter_column('access_code', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('access_code', 'shift_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access_code', 'shift_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('access_code', 'squad_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('media_file',
    sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('access_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['access_code_id'], ['access_code.id'], name='media_file_access_code_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='media_file_pkey')
    )
    op.create_index('ix_media_file_s3_key', 'media_file', ['s3_key'], unique=True)
    op.create_index('ix_media_file_id', 'media_file', ['id'], unique=False)
    # ### end Alembic commands ###
